### ISSUE TITLE
iOS 13 support

### ISSUE THREAD

**Issue by calebpanza** [alicerunsonfedora/ZephyrMac#1]
Any chance these wallpapers can be recreated on the iPhone to make custom iOS 13 light mode/dark mode wallpapers?

**Comment by alicerunsonfedora** [comment]
I don't believe so unless the Wallpapper tool includes this update.

**Comment by alicerunsonfedora** [comment]
After thinking about this, it might be best if you directed this question on the wallpapper repository: https://github.com/mczachurski/wallpapper

**Comment by calebpanza** [comment]
Thanks for the response! I set up an issue on there wallpapper repository. If you’re interested in this, drop a comment on it to help gain some traction!
